#!/bin/bash

# convert move_cube goal to single-goal trajectory
# from: {"difficulty": 3, "goal": {"position": [x, y, z], "orientation": [...]}}
# to: [[0, [x, y, z]]]
goal=$(python3 -c "import json,sys; g=json.loads(sys.argv[1]); print(json.dumps([[0,g['goal']['position']]]))" "$1")
echo "Reformat goal '$1' to '${goal}'"
set -- "${goal}"

# run the script via `ros2 run` (for python scripts a simple symlink would also
# work but using `ros2 run` works for C++ executables as well)

# Examples for Stage 1
# ros2 run rrc_example_package real_move_up_and_down "$@"
# ros2 run rrc_example_package real_trajectory_example_with_gym "$@"
ros2 run rrc_example_package evaluate_stage1 "$@"

# Example for Stage 2
# ros2 run rrc_example_package dice_example_with_gym "$@"
